Make StorageClass configurable
SUSE/caasp-services pull request #33
Opened 2018-03-20 07:32 UTC by lightnet328

Make it possible to set the StorageClass field in Portus configuration file from externally.
I need to set Storage Class field for using Dynamic Volume Provisioning.

2018-03-20 15:47 UTC, mssola commented
@stefsuse could you take a look at this ?

2018-04-09 22:30 UTC, stefsuse requested changes
Please update Chart.yaml version

2018-04-09 22:30 UTC, stefsuse commented on contrib/helm-charts/portus/values.yaml
> +    # storageClass: '-'
uncomment

2018-04-10 08:13 UTC, lightnet328 commented
I sent some pull requests, how do I update version?

2018-04-10 08:24 UTC, lightnet328 commented on contrib/helm-charts/portus/values.yaml
> +    # storageClass: '-'
I wrote such a description for consistency with other charts.
https://github.com/kubernetes/charts/search?q=storageClass+filename%3Avalues.yaml
I'm not picky about it, should I uncomment it?

2018-04-10 17:25 UTC, stefsuse commented on contrib/helm-charts/portus/values.yaml
> +    # storageClass: '-'
I see. No, on second thought it is ok as is thanks.

2018-04-11 17:16 UTC, stefsuse commented
As this change is also included in #38 please close this PR

2018-04-11 21:14 UTC, closed without merging